api_platform:
    title: Knowledge learning Api
    description: 'Api pour accéder aux informations sur les cursus et lessons'
    version: 1.0.0
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
